<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- Meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<meta name="description" content="华农趣事后台管理系统">

		<link rel="stylesheet" href="<?php echo RESOURCE_PATH . '/views/admin/src/libs/vendor/bootstrap/css/bootstrap.min.css';?>">
		<link rel="stylesheet" href="<?php echo RESOURCE_PATH . '/views/admin/src/libs/vendor/themify-icons/themify-icons.css';?>">
		<link rel="stylesheet" href="<?php echo RESOURCE_PATH . '/views/admin/src/libs/vendor/font-awesome/css/font-awesome.min.css';?>">
		<link rel="stylesheet" href="<?php echo RESOURCE_PATH . '/views/admin/src/libs/vendor/jscrollpane/jquery.jscrollpane.css';?>">
		<link rel="stylesheet" href="<?php echo RESOURCE_PATH . '/views/admin/src/libs/vendor/summernote/summernote.css';?>">
		
		<link rel="stylesheet" href="<?php echo RESOURCE_PATH . '/views/admin/src/libs/css/core.css';?>">
		
		<!-- Title -->
		<title>华农趣事平台-后台管理</title>
</head>
<body id="app" class="large-sidebar fixed-sidebar fixed-header skin-1">
	
	<script type="text/javascript" src="<?php echo RESOURCE_PATH . '/views/admin/src/libs/js/jquery-1.12.3.min.js';?>"></script>	
	<script type="text/javascript" src="<?php echo RESOURCE_PATH . '/views/admin/src/libs/vendor/tether/js/tether.min.js';?>"></script>
	<script type="text/javascript" src="<?php echo RESOURCE_PATH . '/views/admin/src/libs/vendor/bootstrap/js/bootstrap.min.js';?>"></script>
	<script type="text/javascript" src="<?php echo RESOURCE_PATH . '/views/admin/src/libs/vendor/detectmobilebrowser/detectmobilebrowser.js';?>"></script>
	<script type="text/javascript" src="<?php echo RESOURCE_PATH . '/views/admin/src/libs/vendor/jscrollpane/jquery.jscrollpane.min.js';?>"></script>

	<script type="text/javascript" src="<?php echo RESOURCE_PATH . '/views/admin/src/libs/js/app.js';?>"></script>

	<script type="text/javascript" src="<?php echo RESOURCE_PATH . '/views/admin/static/lib.js';?>"></script>
	<script type="text/javascript" src="<?php echo RESOURCE_PATH . '/views/admin/static/main.js';?>"></script>
</body>
</html>