<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- Meta tags -->
		<<head>
		<!-- Meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<meta name="description" content="">
		<link rel="stylesheet" href="<?php echo RESOURCE_PATH . '/views/admin/src/libs/vendor/bootstrap/css/bootstrap.min.css';?>">
		<link rel="stylesheet" href="<?php echo RESOURCE_PATH . '/views/admin/src/libs/vendor/themify-icons/themify-icons.css';?>">
		<link rel="stylesheet" href="<?php echo RESOURCE_PATH . '/views/admin/src/libs/css/core.css';?>">
		

		<!-- Title -->
		<title>华农趣事平台-后台管理系统</title>
</head>
	<body class="auth-bg">
		
		<div class="auth">
			<div class="auth-header">
				<h1>华农趣事平台</h1>
				<h6>Welcome! Sign in to access the admin panel</h6>
			</div>
			<div class="container-fluid">
				<div class="row">
					<div class="col-md-4 offset-md-4">
						<form id="login_form">
							<div class="form-group">
								<div class="input-group">
									<input type="text" class="form-control" name="account" placeholder="username" required autocomplete id="username">
									<div class="input-group-addon"><i class="ti-user"></i></div>
								</div>
							</div>
							<div class="form-group">
								<div class="input-group">
								<input type="password" class="form-control" name="password" required placeholder="Password" id="passwd">
									<div class="input-group-addon"><i class="ti-key"></i></div>
								</div>
							</div>
							<div class="form-group">
								<button type="submit" class="btn btn-danger btn-block">登陆</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
		<script src="<?php echo RESOURCE_PATH . '/views/admin/src/libs/js/jquery-1.12.3.min.js';?>"></script>
		<script>		
		$('#login_form').submit(function() {
			var username = $('#username').val(),
				passwd = $('#passwd').val();
				
			if (!username || !passwd) {
				alert('请输入用户名、密码');
				return false;
			}

			$.ajax({
				url: '/adminlogin/opLogin/',
				type:'POST',
				data: {
					account: username,
					password: passwd
				},
				dataType: 'json',

				success(result) {
					if (result.code === 0) {
						var userInfo = {
							admin_id : result.data.data.admin_id,
							admin_name : result.data.data.admin_name,
							cellphone : result.data.data.cellphone,
							register_time : result.data.data.register_time
						};
						try {
							window.location.href = '/admin/index';
							localStorage.setItem('userInfo', JSON.stringify(userInfo));
						} catch (e) {
							window.location.href = 'adminlogin/login';
						}
					} else {
						alert(result.msg);
					}
				},
				fail(result) {
					alert('网络出了点问题，请稍后再试');
				}
			});
			return false;
		});

	</script>
</body>
</html>