<!DOCTYPE html>
<html>
	<head>
		<!-- Meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<meta name="description" content="华农趣事平台平台">

		<link rel="stylesheet" href="../public/
		default/views/thesis/src/libs/css/bootstrap.min.css">
		<link rel="stylesheet" href="<?php echo RESOURCE_PATH . '/views/admin/src/libs/vendor/font-awesome/css/font-awesome.min.css';?>">
		
		
		<!-- Title -->
		<title>华农趣事平台</title>
</head>
<body id="app">
	
	<script type="text/javascript" src="../public/default/views/thesis/static/lib.js"></script>
	<script type="text/javascript" src="../public/default/views/thesis/static/main.js"></script>
<!-- 	<script type="text/javascript" src="../public/default/views/thesis/src/libs/js/jia.js"></script> -->
	<!-- JiaThis Button BEGIN -->

	<script type="text/javascript" src="http://v3.jiathis.com/code/jia.js" charset="utf-8"></script>
</body>
</html>