<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- Meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<meta name="description" content="华农趣事平台平台">

		<link rel="stylesheet" href="<?php echo RESOURCE_PATH . '/views/thesis/src/libs/css/bootstrap.min.css';?>">
		
		

		<!-- Title -->
		<title>华农趣事平台</title>
</head>
<body id="app" class="large-sidebar fixed-sidebar fixed-header skin-1">
	
	<script type="text/javascript" src="<?php echo RESOURCE_PATH . '/views/thesis/static/lib.js';?>"></script>
	<script type="text/javascript" src="<?php echo RESOURCE_PATH . '/views/thesis/static/main.js';?>"></script>
</body>
</html>